# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
locale                   : "ko-KR"
title                    : "이석민 Blog"
title_separator          : "&#124;"
brief-intro: Front-end Dev
subtitle                 : # site tagline that appears below site title in masthead
name                     : "이석민"
description              : "공부하고 기록할 블로그"
url                      : "https://seokmin2016390.github.io/"
baseurl                  : 
repository               : "seokmin2016390/seokmin@donga.co.kr"
permalink: /:year/:month/:day/:title/

# other links
twitter_username:
facebook_username: 
github_username:  
email: lsmm1100@gmail.com
weibo_username: 
zhihu_username: 
linkedIn_username: 
dribbble_username:

# comments
duoshuo_shortname: 
disqus_shortname: disqus_Jlsc9Jo9qd

# statistic analysis
# baidu_tongji_id: cf8506e0ef223e57ff6239944e5d46a4
# google_analytics_id: UA-72449510-4 

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 10

plugins:
  - jekyll-paginate
